$(p1).on('click',function(){
  $(images).css({transform:'translateX(0px)'})
})
$(p2).on('click',function(){
  $(images).css({transform:'translateX(-250px)'})
})
$(p3).on('click',function(){
  $(images).css({transform:'translateX(-500px)'})
})